name: cmms
description: A CMMS Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.13.0
  firebase_storage: ^12.0.0
  responsive_builder: ^0.7.0
  intl: ^0.19.0
  file_picker: ^8.0.0
  logger: ^2.5.0
  url_launcher: ^6.2.4
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  http: ^1.3.0
  flutter_pdfview: ^1.3.2
  firebase_messaging: ^15.2.5
  rxdart: ^0.28.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  dio: ^5.8.0+1
  open_file: ^3.5.10
  permission_handler: ^12.0.0+1
  cloud_functions: ^5.5.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.1

flutter:
  assets:
    - assets/icons/icon.png
    - assets/icons/
  uses-material-design: true
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.14.3